project:
  type: website
  output-dir: docs

website:
  title: "AI Success Factors: Engineering Trust in Deployments"
  navbar:
    right:
      - about.qmd
      - slideindex.qmd
      - icon: github
        href: https://github.com/la3d
      - icon: twitter
        href: https://twitter.com/charlesvardeman
format:
  html:
    theme: journal
    css: styles.css



