project:
  type: website
  output-dir: docs

website:
  title: "AI Success Factors: Engineering Trust in Deployments"
  navbar:
    right:
      - text: "Blog"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Slide Archive"
        href: slideindex.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/la3d
      - icon: twitter
        href: https://twitter.com/charlesvardeman
format:
  html:
    theme: journal
    css: styles.css
    toc: true


